### ISSUE TITLE
Question: additional servers

### ISSUE THREAD

**Issue by ziulev** [BenMcH/bitwarden_rs-docker-compose#4]
I would like to run few things on the same machine at the same time:
bitwarden.my-domain.tld
www.my-domain.tld <- simple website 

How can I do it with your docker compose?

**Comment by BenMcH** [comment]
@ziulev Hi! Currently this would not be possible due to this project's goals. I just wanted something that I could clone to any VPS, run `docker-compose up -d` and forget about it. If you simply want to host bitwarden_rs in docker, I would suggest using the upstream bitwarden_rs installation directly. https://github.com/dani-garcia/bitwarden_rs

You will then need to configure the host mapping, reverse proxy, and SSL certs in whichever web server is fronting your current website.

If you come up with a solution to your issue based on this repo, please feel free to open a pull request! If we can make it more flexible, I am happy to pull in 3rd party changes :smile:

**Comment by BenMcH** [comment]
Closing for now, but I will still gladly accept pull requests for this issue
